class DateRangeError(Exception):...

class SendRequestError(Exception):...

class SpreadsheetNotFound(Exception):...

class WorksheetNotFound(Exception):...

class UpdateWorksheetError(Exception):...

class YamlFileNotFound(Exception):...

class MissingPathToCreds(Exception):...

class MissingSpreadsheetId(Exception):...

class MissingWorksheetId(Exception):...

class MissingAccessToken(Exception):...